package com.alkicorp.bankingsim.model.enums;

public enum TransactionType {
    DEPOSIT,
    WITHDRAWAL,
    LOAN_DISBURSEMENT,
    MORTGAGE_DOWN_PAYMENT,
    MORTGAGE_DOWN_PAYMENT_FUNDING,
    PROPERTY_SALE,
    PAYROLL_DEPOSIT,
    SPENDING,
    RENT_PAYMENT,
    SAVINGS_DEPOSIT,
    SAVINGS_WITHDRAWAL,
    PAYMENT_FAILED,
    MORTGAGE_PAYMENT,
    AUTO_LOAN_PAYMENT,
    PERSONAL_LOAN_PAYMENT,
    CREDIT_CARD_PAYMENT
}
